"""empty message

Revision ID: 07027a7e8f7b
Revises: a99434152f76
Create Date: 2020-01-29 16:00:27.761663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07027a7e8f7b'
down_revision = 'a99434152f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
