"""empty message

Revision ID: 4ec0f6893cbf
Revises: ab49c4f19481
Create Date: 2020-01-29 16:50:28.762180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ec0f6893cbf'
down_revision = 'ab49c4f19481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('accounts', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_on')
    op.drop_column('users', 'created_on')
    op.drop_column('accounts', 'updated_on')
    op.drop_column('accounts', 'created_on')
    # ### end Alembic commands ###
