"""empty message

Revision ID: cfb6d916e213
Revises: 317034ccb384
Create Date: 2020-02-05 14:27:07.636785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb6d916e213'
down_revision = '317034ccb384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint('accounts_owner_fkey', 'accounts', type_='foreignkey')
    op.create_foreign_key(None, 'accounts', 'users', ['owner_id'], ['id'])
    op.drop_column('accounts', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.create_foreign_key('accounts_owner_fkey', 'accounts', 'users', ['owner'], ['id'])
    op.drop_column('accounts', 'owner_id')
    # ### end Alembic commands ###
